name: Run OPA Tests

on:
  deployment_status:
    branches-ignore:
      - main

jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v1
      with:
        version: latest

    - name: Run OPA Tests
      run: opa test tests/*.rego -v
